spring.application.name=FoodSharePI


# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/FoodSharePI?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Port du serveur
server.port=8091




# ========================
# CONFIGURATION EMAIL ESPRIT (hébergé sur Gmail)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mariem.dakhli@esprit.tn
spring.mail.password=hkdp prup sjub kpiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8

# Email expéditeur
app.email.from=mariem.dakhli@esprit.tn

# URL Frontend (Angular)
app.frontend.url=http://localhost:4200

# Logs de transaction détaillés
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.transaction=DEBUG


# Static resources
spring.web.resources.static-locations=classpath:/static/,file:./uploads/